; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sun Jul 26 2020 22:38:02 GMT+0200 (Central European Summer Time)
M280 P3 S10 I1 ; deploy BLTouch

