; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Jul 18 2020 19:34:42 GMT+0200 (Central European Summer Time)

