; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Jul 18 2020 19:34:42 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

